---
- name: Running Bind9 Playbook
  hosts: bind9
  vars_files:
    - variable/main.yml
  tasks:
    - name: Install Bind9
      become: true
      ansible.builtin.apt:
        name:
          bind9

    - name: Configure Bind9
      become: true
      ansible.builtin.copy:
        content: |
          include "/etc/bind/named.conf.default-zones";

          key "{{ bind9.tsig.name }}" {
            algorithm {{ bind9.tsig.algorithm }};
            secret "{{ bind9.tsig.key }}";
          };

          acl internal {
            {% for cidr in bind9.cidr_allowed_access_list %}
            {{ cidr }};
            {% endfor %}
          };

          options {
            directory "/var/cache/bind";

            forwarders {
              {% for forwarder in bind9.forwarders %}
              {{ forwarder }};
              {% endfor %}
            };

            dnssec-validation auto;
            allow-query { internal; };
            listen-on-v6 { any; };
          };

          {% for forward_zone in bind9.forward_zones %}
          zone "{{ forward_zone }}" {
            type master;
            file "/var/lib/bind/{{ forward_zone }}";
            update-policy { grant {{ bind9.tsig.name }} zonesub any; };
          };
          {% endfor %}

          {% for reverse_zone in bind9.reverse_zones %}
          zone "{{ reverse_zone }}" {
            type master;
            file "/var/lib/bind/{{ reverse_zone }}";
            update-policy { grant {{ bind9.tsig.name }} zonesub any; };
          };
          {% endfor %}
        dest: /etc/bind/named.conf
        owner: root
        group: bind
        mode: "0640"
      notify: Restart Bind9

    - name: Configure forward zones
      become: true
      ansible.builtin.copy:
        content: |
          $TTL    604800
          @       IN      SOA     ns.{{ item }}. root.{{ item }}. (
                   2       ; Serial
              604800       ; Refresh
               86400       ; Retry
             2419200       ; Expire
              604800       ; Negative Cache TTL
          )
          @       IN      NS      ns.{{ item }}.
          ns      IN      A       {{ ip_address }}
        dest: /var/lib/bind/{{ item }}
        owner: bind
        group: bind
        mode: "0640"
      notify: Restart Bind9
      loop: "{{ bind9.forward_zones }}"

    - name: Configure reverse zones
      become: true
      ansible.builtin.copy:
        content: |
          $TTL 604800
          @ IN SOA ns.{{ bind9.forward_zones[0] }}. root.{{ bind9.forward_zones[0] }}. (
                   2 ; Serial
              604800 ; Refresh
               86400 ; Retry
             2419200 ; Expire
              604800 ; Negative Cache TTL
          )
          @       IN       NS       ns.{{ bind9.forward_zones[0] }}.
        dest: /var/lib/bind/{{ item }}
        owner: bind
        group: bind
        mode: "0640"
      notify: Restart Bind9
      loop: "{{ bind9.reverse_zones }}"

  handlers:
    - name: Restart Bind9
      become: true
      ansible.builtin.systemd_service:
        name: bind9.service
        state: restarted
