---
- name: Installing Bind9 dns server
  hosts: bind9
  vars_files:
    - variables/bind9-config.yml
  tasks:
    - name: Installing bind9
      become: true
      ansible.builtin.apt:
        name:
          bind9

    - name: Configuring bind9
      become: true
      ansible.builtin.copy:
        content: |
          include "/etc/bind/named.conf.default-zones";

          key "{{ tsig_name }}" {
            algorithm {{ tsig_algorithm }};
            secret "{{ tsig_key }}";
          };

          acl internal {
            {% for cidr in cidr_list %}
            {{ cidr }};
            {% endfor %}
          };

          options {
            directory "/var/cache/bind";

            forwarders {
              {% for dns_forwarder in dns_forwarders %}
              {{ dns_forwarder }};
              {% endfor %}
            };

            dnssec-validation auto;
            allow-query { internal; };
            listen-on-v6 { any; };
          };

          {% for zone in forward_zone %}
          zone "{{ zone }}" {
            type master;
            file "/var/lib/bind/db.{{ zone }}";
            update-policy { grant {{ tsig_name }} zonesub any; };
          };
          {% endfor %}

          {% for zone in reverse_zone %}
          zone "{{ zone }}.in-addr.arpa" {
            type master;
            file "/var/lib/bind/{{ zone }}.in-addr.arpa";
            update-policy { grant {{ tsig_name }} zonesub any; };
          };
          {% endfor %}
        dest: /etc/bind/named.conf
        owner: root
        group: bind
        mode: "0640"

    - name: Adding forward zones
      become: true
      ansible.builtin.copy:
        content: |
          $TTL    604800
          @       IN      SOA     ns.{{ item }}. root.{{ item }}. (
                   2       ; Serial
              604800       ; Refresh
               86400       ; Retry
             2419200       ; Expire
              604800       ; Negative Cache TTL
          )
          @       IN      NS      ns.{{ item }}.
          ns      IN      A       {{ ansible_all_ipv4_addresses }}
        dest: /var/lib/bind/db.{{ item }}
        owner: bind
        group: bind
        mode: "0640"
      loop: "{{ forward_zone }}"

    - name: Adding reverse zones
      become: true
      ansible.builtin.copy:
        content: |
          $TTL 604800
          @ IN SOA ns.{{ forward_zone[0] }}. root.{{ forward_zone[0] }}. (
                   2 ; Serial
              604800 ; Refresh
               86400 ; Retry
             2419200 ; Expire
              604800 ; Negative Cache TTL
          )
          @       IN       NS       ns.{{ forward_zone[0] }}.
        dest: /var/lib/bind/{{ item }}.in-addr.arpa
        owner: bind
        group: bind
        mode: "0640"
      loop: "{{ reverse_zone }}"

    - name: Reloading Bind9
      become: true
      ansible.builtin.systemd_service:
        name: bind9.service
        state: restarted
