---
- name: Installing haproxy reverse proxy
  hosts: haproxy
  vars_files:
    - variables/haproxy-config.yml
  tasks:
    - name: Installing haproxy
      become: true
      ansible.builtin.apt:
        name:
          haproxy

    - name: Adding Haproxy configuring
      become: true
      ansible.builtin.copy:
        content: |
          frontend blocky
          bind *:25565
          mode tcp
          tcp-request inspect-delay 5s

          {% for server in backend_servers %}
          acl is_{{ server.name }} payload(4, {{ server.domain | length + 1 }}) -m sub {{ server.domain }}
          {% endfor %}

          tcp-request content accept if {% for server in backend_servers -%}
          is_{{ server.name }}{% if not loop.last %} | {% endif %}
          {%- endfor %}


          {% for server in backend_servers %}use_backend {{ server.name }}_backend if is_{{ server.name }}
          {% endfor %}

          {% for server in backend_servers %}
          backend {{ server.name }}_backend
            server {{ server.name }} {{ server.address }}

          {% endfor %}
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0640"

    - name: Restart haproxy
      become: true
      ansible.builtin.systemd_service:
        name: haproxy.service
        state: restarted
