[pki-server]
"" ip_address="" domain_name=""

[mysql]
"" ip_address="" domain_name=""

[bind9]
"" ip_address="" domain_name=""

[vaultwarden]
"" ip_address="" domain_name=""

[wordpress]
"" ip_address="" domain_name=""

[nextcloud]
"" ip_address="" domain_name=""

[pterodactyl-panel]
"" ip_address="" domain_name=""

[pterodactyl-wing]
"" ip_address="" domain_name="" uuid="" token_id="" token=""

[zabbix-server]
"" ip_address="" domain_name=""

[nginx]
"" ip_address="" domain_name=""

[haproxy]
"" ip_address="" domain_name=""
