- name: Running CA certificate install Playbook
  hosts: all
  vars_files:
    - variable/main.yml
  tasks:
    - name: Install Certificate Authority certificate
      become: true
      ansible.builtin.get_url:
        url: "{{ url.get_ca }}"
        dest: /usr/local/share/ca-certificates/PersonalCa.crt
        owner: root
        group: root
        mode: "0644"
      notify: Reload certificate list

  handlers:
    - name: Reload certificate list
      become: true
      ansible.builtin.command: update-ca-certificates
