---
- name: MySQL server
  hosts: mysql
  tasks:
    - name: Installing MySQL
      become: true
      ansible.builtin.apt:
        name:
          - mysql-server
          - python3-pymysql

    - name: Enabling MySQL
      become: true
      ansible.builtin.systemd_service:
        name: mysql
        state: started
        enabled: true

    - name: Update MySQL bind-address
      become: true
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regex }}"
        line: "{{ item.out }}"
      loop:
        - { regex: '^bind-address', out: 'bind-address = 0.0.0.0' }
        - { regex: '^mysqlx-bind-addres', out: 'mysqlx-bind-address = 0.0.0.0' }

    - name: Restart MySQL service
      become: true
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Check if it was imported
      become: true
      ansible.builtin.stat:
        path: /var/lib/mysql/.backup_imported
      register: stat_result

    - name: Copy dump file to remote host
      ansible.builtin.copy:
        src: files/mysql.sql
        dest: /tmp/mysql.sql
        mode: "0644"
      when: not stat_result.stat.exists

    - name: Import MySQL dump
      become: true
      community.mysql.mysql_db:
        name: all
        state: import
        target: /tmp/mysql.sql
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: not stat_result.stat.exists

    - name: Create marker file after import
      become: true
      ansible.builtin.file:
        path: /var/lib/mysql/.backup_imported
        state: touch
        owner: mysql
        group: mysql
        mode: "0640"
