---
- name: MySQL server
  hosts: mysql
  vars_files:
    - variables/main.yml
  tasks:
    - name: Install MySQL
      become: true
      ansible.builtin.apt:
        name:
          - mysql-server
          - python3-pymysql

    - name: Enable MySQL
      become: true
      ansible.builtin.systemd_service:
        name: mysql
        state: started
        enabled: true

    - name: Update MySQL bind-address
      become: true
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^#?\\s*{{ item.regex }}"
        line: "{{ item.out }}"
      notify: Restart MySQL
      loop:
        - { regex: 'bind-address', out: 'bind-address = 0.0.0.0' }
        - { regex: 'mysqlx-bind-addres', out: 'mysqlx-bind-address = 0.0.0.0' }
        - { regex: 'port', out: "port = {{ mysql.port }}" }

    - name: Create MySQL users
      become: true
      community.mysql.mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ mysql.username }}"
        password: "{{ mysql.password }}"
        host: "{{ mysql.mysql_host }}"
        priv: "{{ mysql.privileges }}"
        state: present

    - name: Select query to test_db with named_args
      community.mysql.mysql_query:
        login_user: "{{ mysql.username }}"
        login_password: "{{ mysql.password }}"
        login_host: "{{ mysql.address }}"
        login_port: "{{ mysql.port }}"
        query: SET GLOBAL log_bin_trust_function_creators = 1;

  handlers:
    - name: Restart MySQL
      become: true
      ansible.builtin.service:
        name: mysql
        state: restarted
