---
- name: MySQL server
  hosts: mysql
  vars_files:
    - variables/config/mysql.yml
  tasks:
    - name: Install MySQL
      become: true
      ansible.builtin.apt:
        name:
          - mysql-server
          - python3-pymysql

    - name: Enable MySQL
      become: true
      ansible.builtin.systemd_service:
        name: mysql
        state: started
        enabled: true

    - name: Update MySQL bind-address
      become: true
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^#?\\s*{{ item.regex }}"
        line: "{{ item.out }}"
      notify: Restart MySQL
      loop:
        - { regex: 'bind-address', out: 'bind-address = 0.0.0.0' }
        - { regex: 'mysqlx-bind-addres', out: 'mysqlx-bind-address = 0.0.0.0' }
        - { regex: 'port', out: "port = {{ mysql.port }}" }

    - name: Create MySQL users
      become: true
      community.mysql.mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ username }}"
        password: "{{ password }}"
        host: "{{ mysql_host }}"
        priv: "{{ privileges }}"
        state: present

  handlers:
    - name: Restart MySQL
      become: true
      ansible.builtin.service:
        name: mysql
        state: restarted
