---
- name: MySQL server
  hosts: mysql-test
  vars_files:
    - variables/mysql-credentials.yml
    - variables/mysql-database-dumps.yml
  tasks:
    - name: Installing MySQL
      become: true
      ansible.builtin.apt:
        name:
          - mysql-server
          - python3-pymysql

    - name: Enabling MySQL
      become: true
      ansible.builtin.systemd_service:
        name: mysql
        state: started
        enabled: true

    - name: Update MySQL bind-address
      become: true
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regex }}"
        line: "{{ item.out }}"
      loop:
        - { regex: '^bind-address', out: 'bind-address = 0.0.0.0' }
        - { regex: '^mysqlx-bind-addres', out: 'mysqlx-bind-address = 0.0.0.0' }

    - name: Restart MySQL service
      become: true
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Check if database exists
      become: true
      community.mysql.mysql_query:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query: "SHOW DATABASES LIKE '{{ item.database_dump_name }}';"
      loop: "{{ mysql_database_dumps }}"
      register: db_check


    - name: Copy dump file to remote host
      ansible.builtin.copy:
        src: "{{ item.item.local_dump_path }}"
        dest: "{{ item.item.remote_temp_path }}"
        mode: "0644"
      loop: "{{ db_check.results }}"
      when: item.rowcount[0] == 0

    - name: Import MySQL dump
      become: true
      community.mysql.mysql_db:
        name: "{{ item.item.database_dump_name }}"
        state: import
        target: "{{ item.item.remote_temp_path }}"
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      loop: "{{ db_check.results }}"
      when: item.rowcount[0] == 0


    - name: Deleting dumps files from remote machine
      ansible.builtin.file:
        dest: "{{ item.item.remote_temp_path }}"
        state: absent
      loop: "{{ db_check.results }}"
      when: item.rowcount[0] == 0

    - name: Creating mysql users
      become: true
      community.mysql.mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ item.db_user }}"
        password: "{{ item.db_password }}"
        host: "{{ item.mysql_host }}"
        priv: "{{ item.privileges }}"
        state: present
      loop: "{{ mysql_users_profile }}"
