---
- name: Installing NextCloud
  hosts: nextcloud
  vars_files:
    - variables/nextcloud-config.yml
    - variables/ssl-default-values.yml
  tasks:
    - name: Installing PHP modules
      become: true
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-gd
          - php-mysql
          - php-curl
          - php-mbstring
          - php-intl
          - php-gmp
          - php-xml
          - php-imagick
          - php-zip
          - zip

    - name: Getting the install script
      become: true
      ansible.builtin.get_url:
        url: https://download.nextcloud.com/server/releases/latest.zip
        dest: /tmp/
        mode: "0655"


    - name: Extracting file
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/latest.zip
        dest: "{{ nextcloud_path }}"
        owner: www-data
        group: www-data

    - name: Installing ssl cert for https connection
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml
      vars:
        subject_alt_name_options:
          - "DNS:{{ domain_name }}"
          - "IP:{{ ip_address }}"


    - name: Installing PHP modules
      become: true
      ansible.builtin.apt:
        name:
          apache2

    - name: Adding apache config
      become: true
      ansible.builtin.copy:
        content: |
          <VirtualHost *:80>
            RewriteEngine On
            RewriteCond %{HTTPS} !=on
            RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
          </VirtualHost>

          <VirtualHost *:443>
              DocumentRoot "{{ nextcloud_path }}/nextcloud"

              AllowEncodedSlashes On

              php_value upload_max_filesize 100M
              php_value post_max_size 100M

              <Directory "{{ nextcloud_path }}/nextcloud">
                  Require all granted
                  AllowOverride all
              </Directory>

              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/{{ PublicKey }}
              SSLCertificateKeyFile /etc/ssl/private/{{ PrivateKey }}
          </VirtualHost>
        dest: /etc/apache2/sites-available/nextcloud.conf
        owner: root
        group: root
        mode: '0644'

    - name: Disable default Apache site
      become: true
      ansible.builtin.command: a2dissite 000-default.conf
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf

    - name: Enable Apache site
      become: true
      ansible.builtin.command: a2ensite nextcloud.conf
      args:
        creates: /etc/apache2/sites-enabled/nextcloud.conf

    - name: Enabling apache mods
      become: true
      ansible.builtin.command: a2enmod ssl rewrite headers env dir mime

    - name: Restart apache
      become: true
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: Check if Nextcloud is already installed
      become: true
      ansible.builtin.stat:
        path: "{{ nextcloud_path }}/nextcloud/config/config.php"
      register: nextcloud_config

    - name: Generating config file and database
      become: true
      ansible.builtin.command: >
        sudo -u www-data php occ maintenance:install
        --database "{{ database_connection.type }}"
        --database-host "{{ database_connection.host }}"
        --database-port "{{ database_connection.port }}"
        --database-name "{{ database_connection.name }}"
        --database-user "{{ database_connection.user }}"
        --database-pass "{{ database_connection.password }}"
        --admin-user "{{ admin_credential.user }}"
        --admin-pass "{{ admin_credential.password }}"
      args:
        chdir: "{{ nextcloud_path }}/nextcloud"
      when: not nextcloud_config.stat.exists

    - name: Setting trusted domains
      become: true
      ansible.builtin.command: >
        sudo -u www-data php occ config:system:set
        trusted_domains "{{ trusted_domains_index }}" --value="{{ item }}"
      args:
        chdir: "{{ nextcloud_path }}/nextcloud"
      loop: "{{ trusted_domains }}"
      loop_control:
        index_var: trusted_domains_index
