---
- name: Installing PKI server
  hosts: pki-server
  vars_files:
    - variables/pki-server-config.yml
    - variables/credentials.yml

  tasks:
    - name: Installing needed dependencies on ubuntu
      become: true
      ansible.builtin.apt:
        name:
          - git

    - name: Installing NodeJS
      ansible.builtin.include_tasks: tasks/nodejs-install.yml

    - name: Cloning PKI API SERVER
      become: true
      ansible.builtin.git:
        repo: "{{ git_repo_link }}"
        dest: "{{ project_path }}"
        version: main
        update: true

    - name: Changing permissions
      become: true
      ansible.builtin.file:
        path: "{{ project_path }}"
        owner: "{{ remote_ansible_user }}"
        recurse: true

    - name: Creating env file
      ansible.builtin.copy:
        remote_src: true
        src: "{{ project_path }}/.envExample"
        dest: "{{ project_path }}/.env"
        owner: "{{ remote_ansible_user }}"
        group: root
        mode: "740"


    - name: Setting up password to the root password
      ansible.builtin.lineinfile:
        path: "{{ project_path }}/.env"
        regexp: "{{ item.regex }}"
        line: "{{ item.value }}"
      loop:
        - { regex: "^CA_root_password", value: "CA_root_password={{ ca_cert_passphrase }}" }
        - { regex: "^node_hostname", value: "node_hostname={{ nodejs_hostname }}" }
        - { regex: "^node_port", value: "node_port={{ nodejs_port }}" }

    - name: Creating directories for the project
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ remote_ansible_user }}"
        group: root
        mode: "0740"
      loop:
        - "{{ project_path }}/ca"
        - "{{ project_path }}/reqs"
        - "{{ project_path }}/issued"

    - name: Generate CA private key (if not existing)
      ansible.builtin.command: >
        openssl genrsa
        -aes256
        -passout pass:"{{ ca_cert_passphrase }}"
        -out "{{ project_path }}/ca/ca-key.pem"
        4096
      args:
        creates: "{{ project_path }}/ca/ca-key.pem"

    - name: Generate CA self-signed certificate (if not existing)
      ansible.builtin.command: >
        openssl req -x509 -new -nodes
        -key "{{ project_path }}/ca/ca-key.pem"
        -days 365
        -out "{{ project_path }}/ca/ca.pem"
        -subj "/C={{ country }}/ST={{ country_state }}/L={{ city }}/O={{ organization }}/OU={{ organizational_unit }}/CN={{ common_name }}"
        -passin pass:"{{ ca_cert_passphrase }}"
      args:
        creates: "{{ project_path }}/ca/ca.pem"

    - name: Set permissions on CA key and certificate
      ansible.builtin.file:
        path: "{{ item.location }}"
        mode: "{{ item.permission }}"
      loop:
        - { location: "{{ project_path }}/ca/ca-key.pem", permission: "0400" }
        - { location: "{{ project_path }}/ca/ca.pem", permission: "0440" }

    - name: Installing npm dependencies
      community.general.npm:
        path: "{{ project_path }}"

    - name: Adding a systemd services
      become: true
      ansible.builtin.copy:
        content: |
          [Unit]
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory={{ project_path }}
          ExecStart=/usr/bin/node --env-file=.env index.js
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/{{ project_name }}.service"
        mode: "0555"

    - name: Starting the project service
      become: true
      ansible.builtin.systemd:
        state: restarted
        enabled: true
        name: "{{ project_name }}.service"
