---
- name: Running Pterodactyl Wing Playbook
  hosts: pterodactyl-wing
  vars_files:
    - variables/main.yml
  tasks:
    - name: Install dependency
      become: true
      ansible.builtin.apt:
        name:
          - curl

    - name: Import Docker install playbook
      ansible.builtin.include_tasks: tasks/docker-install.yml

    - name: Download Pterodactyl Wings binary
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
        dest: /usr/local/bin/wings
        mode: "0755"

    - name: Adding Pterodactyl directory
      become: true
      ansible.builtin.file:
        state: directory
        dest: /etc/pterodactyl
        owner: root
        group: root
        mode: "0640"

    - name: Installing ssl cert for https connection
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml

    - name: Add pterodactyl directory
      become: true
      ansible.builtin.copy:
        content: |
          debug: false
          uuid: {{ uuid }}
          token_id: {{ token_id }}
          token: {{ token }}
          api:
            host: 0.0.0.0
            port: 8080
            ssl:
              enabled: true
              cert: /etc/ssl/certs/{{ certificate.public_key }}
              key: /etc/ssl/private/{{ certificate.private_key }}
            upload_limit: 100
          system:
            data: /var/lib/pterodactyl/volumes
            sftp:
              bind_port: 2022
          allowed_mounts: []
          remote: '{{ pterodactyl.wing.remote_server }}'
        dest: /etc/pterodactyl/config.yml
        owner: root
        group: root
        mode: "0640"
      notify: Restart Pterodactyl Wing

    - name: Add pterodactyl directory
      become: true
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Pterodactyl Wings Daemon
          After=docker.service
          Requires=docker.service
          PartOf=docker.service

          [Service]
          User=root
          WorkingDirectory=/etc/pterodactyl
          LimitNOFILE=4096
          PIDFile=/var/run/wings/daemon.pid
          ExecStart=/usr/local/bin/wings
          Restart=on-failure
          StartLimitInterval=180
          StartLimitBurst=30
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/wings.service
        owner: root
        group: root
        mode: "0755"
      notify: Restart daemon reload

    - name: Starting the project service
      become: true
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: wings.service

  handlers:
    - name: Restart Pterodactyl Wing
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: wings.service

    - name: Restart daemon reload
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
