---
- name: Running SNMP Playbook
  hosts: all
  vars_files:
    - variables/config/snmp.yml
  tasks:
    - name: Install SNMP
      become: true
      ansible.builtin.apt:
        name:
          - snmpd
          - libsnmp-dev

    - name: Enable SNMPD
      become: true
      ansible.builtin.service:
        name: snmpd
        state: started
        enabled: true

    - name: Configure SNMP
      become: true
      ansible.builtin.copy:
        content: |
          sysLocation    Sitting on the Dock of the Bay
          sysContact     Me <me@example.org>
          sysServices    72

          master  agentx
          agentaddress  udp:161

          view   systemonly  included   .1.3.6.1.2.1.1
          view   systemonly  included   .1.3.6.1.2.1.25.1

          rocommunity {{ community_string }} {{ listening_address }}

          rouser authPrivUser authpriv -V systemonly

          includeDir /etc/snmp/snmpd.conf.d
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: Debian-snmp
        mode: "0640"
      notify: Restart SNMPD

  handlers:
    - name: Restart SNMPD
      become: true
      ansible.builtin.service:
        name: snmpd
        state: restarted
