---
- name: Running VaultWarden Playbook
  hosts: vaultwarden
  vars_files:
    - variables/config/mysql.yml
    - variables/config/pki-server.yml
    - variables/system/certificate.yml
    - variables/config/vaultwarden.yml
  tasks:
    - name: Install dependacies
      become: true
      ansible.builtin.apt:
        name:
          - python3-pymysql

    - name: Import Docker install task
      ansible.builtin.include_tasks: tasks/docker-install.yml

    - name: SSL certificate request generator
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml

    - name: Create VaultWarden database
      become: true
      community.mysql.mysql_db:
        name: "{{ database.name }}"
        state: present
        login_user: "{{ username }}"
        login_password: "{{ password }}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"

    - name: Create VaultWarden users
      become: true
      community.mysql.mysql_user:
        login_user: "{{ username }}"
        login_password: "{{ password }}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"
        column_case_sensitive: true
        name: "{{ database.user }}"
        password: "{{ database.password }}"
        host: "%"
        priv:
          "{{ database.name }}.*:ALL"
        state: present

    - name: Create VaultWarden directory
      become: true
      ansible.builtin.file:
        path: /var/opt/vaultwarden
        state: directory
        owner: root
        group: root
        mode: "0640"

    - name: Create docker compose file
      become: true
      ansible.builtin.copy:
        dest: /var/opt/vaultwarden/compose.yml
        content: |
          services:
            vaultwarden:
              image: vaultwarden/server:latest
              container_name: vaultwarden
              restart: unless-stopped
              environment:
                DATABASE_URL: "{{ database.engine }}://{{ database.user }}:{{ database.password }}@{{ database.host }}:{{ database.port }}/{{ database.name }}"
                ROCKET_TLS: '{certs="/etc/ssl/certs/{{ public_key }}", key="/etc/ssl/private/{{ private_key }}"}'
              volumes:
                - ./vw-data/:/data/
                - /etc/ssl:/etc/ssl
              ports:
                - 443:80
        owner: root
        group: root
        mode: "0640"

    - name: Deploy VaultWarden docker
      become: true
      community.docker.docker_compose_v2:
        project_src: /var/opt/vaultwarden
        files: compose.yml
        state: present
