---
- name: Installing vaultwarden
  hosts: vaultwarden
  vars_files:
    - variables/vaultwarden-config.yml
    - variables/ssl-default-values.yml
  tasks:
    - name: Installing docker
      ansible.builtin.include_tasks: tasks/docker-install.yml

    - name: Installing ssl cert for https connection
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml
      vars:
        subject_alt_name_options:
          - "DNS:{{ domain_name }}"

    - name: Restart Docker service
      become: true
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Adding vaultwarden directory
      become: true
      ansible.builtin.file:
        path: /var/opt/vaultwarden
        state: directory
        owner: root
        group: root
        mode: '0640'

    - name: Adding docker-composer file
      become: true
      ansible.builtin.copy:
        path: /var/opt/vaultwarden/docker-compose.yml
        content: |
          services:
            vaultwarden:
              image: vaultwarden/server:latest
              container_name: vaultwarden
              restart: unless-stopped
              environment:
                DATABASE_URL: "{{ database_connection_url }}"
                ROCKET_TLS: '{certs="/etc/ssl/certs/{{ PublicKey }}", key="/etc/ssl/private/{{ PrivateKey }}"}'
              volumes:
                - ./vw-data/:/data/
                - /etc/ssl:/etc/ssl
              ports:
                - 443:80
        owner: root
        group: root
        mode: '0640'

    - name: Deploying docker
      become: true
      community.docker.docker_compose_v2:
        project_src: /var/opt/vaultwarden
        files: docker-compose.yml
        state: present
