---
- name: Running VaultWarden Playbook
  hosts: vaultwarden
  vars_files:
    - variable/main.yml
  tasks:
    - name: Install depe
      become: true
      ansible.builtin.apt:
        name:
          - python3-pymysql

    - name: Import Docker install task
      ansible.builtin.include_tasks: tasks/docker-install.yml

    - name: SSL certificate request generator
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml

    - name: Create VaultWarden database
      become: true
      community.mysql.mysql_db:
        name: "{{ vault.db.name }}"
        state: present
        login_user: "{{ mysql.username }}"
        login_password: "{{ mysql.password }}"
        login_host: "{{ mysql.address }}"
        login_port: "{{ mysql.port }}"

    - name: Create VaultWarden users
      become: true
      community.mysql.mysql_user:
        login_user: "{{ mysql.username }}"
        login_password: "{{ mysql.password }}"
        login_host: "{{ mysql.address }}"
        login_port: "{{ mysql.port }}"
        column_case_sensitive: true
        name: "{{ vault.db.user }}"
        password: "{{ vault.db.password }}"
        host: "%"
        priv:
          "{{ vault.db.name }}.*:ALL"
        state: present

    - name: Create VaultWarden directory
      become: true
      ansible.builtin.file:
        path: /var/opt/vaultwarden
        state: directory
        owner: root
        group: root
        mode: "0640"

    - name: Create docker compose file
      become: true
      ansible.builtin.copy:
        dest: /var/opt/vaultwarden/compose.yml
        content: |
          services:
            vaultwarden:
              image: vaultwarden/server:latest
              container_name: vaultwarden
              restart: unless-stopped
              environment:
                DATABASE_URL: "{{ vault.db.engine }}://{{ vault.db.user }}:{{ vault.db.password }}@{{ vault.db.host }}:{{ vault.db.port }}/{{ vault.db.name }}"
                ROCKET_TLS: '{certs="/etc/ssl/certs/{{ certificate.public_key }}", key="/etc/ssl/private/{{ certificate.private_key }}"}'
              volumes:
                - ./vw-data/:/data/
                - /etc/ssl:/etc/ssl
              ports:
                - 443:80
        owner: root
        group: root
        mode: "0640"

    - name: Deploy VaultWarden docker
      become: true
      community.docker.docker_compose_v2:
        project_src: /var/opt/vaultwarden
        files: compose.yml
        state: present
