---
- name: Running Zabbix Agent 2 Playbook
  hosts: all
  vars_files:
    - variables/main.yml
  tasks:
    - name: Install Zabbix repository
      become: true
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb

    - name: Update caches
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Zabbix Agent 2 and Agent 2 plugins
      become: true
      ansible.builtin.apt:
        name:
          - zabbix-agent2
          # Zabbix agent 2 plugins
          - zabbix-agent2-plugin-mongodb
          - zabbix-agent2-plugin-mssql
          - zabbix-agent2-plugin-postgresql

    - name: Enable Zabbix agent 2
      become: true
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: true

    - name: Configure Zabbix Agent 2
      become: true
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^#?\\s*{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      notify: Restart Zabbix Agent
      loop:
        - { key: Server, value: "{{ zabbix.agent.listening.server }}" }
        - { key: ListenPort, value: "{{ zabbix.agent.listening.port }}" }
        - { key: ServerActive, value: "{{ zabbix.agent.listening.server }}" }
        - { key: Hostname, value: "{{ ansible_hostname }}" }
        - { key: HostnameItem, value: "{{ ansible_hostname }}" }
        - { key: HostMetadata, value: "zabbix_{{ ansible_hostname }}" }
        - { key: HostMetadataItem, value: "{{ ansible_hostname }}" }

  handlers:
    - name: Restart Zabbix Agent
      become: true
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
