---
- name: Running Zabbix Server Playbook
  hosts: zabbix-server
  vars_files:
    - variables/main.yml
  tasks:
    - name: Install Zabbix repository
      become: true
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb

    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Zabbix server, FrontEnd, Agent2, Apache, PHP and Zabbix Agent2 plugins
      become: true
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-sql-scripts
          - zabbix-agent2
          - python3-pymysql
          - apache2
          - php
          # Install Zabbix Agent2 plugins
          - zabbix-agent2-plugin-mongodb
          - zabbix-agent2-plugin-mssql
          - zabbix-agent2-plugin-postgresql

    - name: Enable Apache2, Zabbix server and agent server
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent2
        - apache2

    - name: Create Zabbix database
      become: true
      community.mysql.mysql_db:
        name: "{{ zabbix.server.database.name }}"
        state: present
        login_user: "{{ mysql.username }}"
        login_password: "{{ mysql.password }}"
        login_host: "{{ mysql.address }}"
        login_port: "{{ mysql.port }}"
        encoding: utf8mb4
        collation: utf8mb4_bin
      notify: Import Zabbix Database Dump

    - name: Create MySQL users
      become: true
      community.mysql.mysql_user:
        login_user: "{{ mysql.username }}"
        login_password: "{{ mysql.password }}"
        login_host: "{{ mysql.address }}"
        login_port: "{{ mysql.port }}"
        column_case_sensitive: true
        name: "{{ zabbix.server.database.user }}"
        password: "{{ zabbix.server.database.password }}"
        host: "%"
        priv:
          "{{ zabbix.server.database.name }}.*:ALL"
        state: present

    - name: SSL certificate request generator
      ansible.builtin.include_tasks: tasks/adding-ssl-cert.yml

    - name: Configuring locale
      become: true
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present
      notify: Restart Apache2

    - name: Enable Apache2 mods for HTTPS
      become: true
      community.general.apache2_module:
        state: present
        name: "{{ item }}"
        identifier: "{{ item }}_module"
        ignore_configcheck: true
      notify: Restart Apache2
      loop:
        - rewrite
        - headers
        - ssl
        - env
        - dir
        - mime

    - name: Configuring Zabbix apache config
      become: true
      ansible.builtin.copy:
        content: |
          <VirtualHost *:80>
              ServerName {{ domain_name }}

              RewriteEngine On
              RewriteCond %{HTTPS} !=on
              RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
          </VirtualHost>
          <VirtualHost *:443>
              DocumentRoot "/usr/share/zabbix/ui"

              ServerName {{ domain_name }}

              AllowEncodedSlashes On

              php_value post_max_size 16M
              php_value max_execution_time 300
              php_value max_input_time 300

              <Directory "/usr/share/zabbix/ui">
                  Require all granted
                  AllowOverride all
              </Directory>

              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/{{ certificate.public_key }}
              SSLCertificateKeyFile /etc/ssl/private/{{ certificate.private_key }}
          </VirtualHost>
        dest: /etc/apache2/sites-enabled/zabbix.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Apache2

    - name: Disable default Apache site
      become: true
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: Restart Apache2

    - name: Configuring Zabbix Server
      become: true
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#?\\s*{{ item.option }}="
        line: "{{ item.option }}={{ item.value }}"
      notify: Restart Zabbix Server
      loop:
        - { option: DBHost, value: "{{ zabbix.server.database.host }}" }
        - { option: DBPort, value: "{{ zabbix.server.database.port }}" }
        - { option: DBName, value: "{{ zabbix.server.database.name }}" }
        - { option: DBUser, value: "{{ zabbix.server.database.user }}" }
        - { option: DBPassword, value: "{{ zabbix.server.database.password }}" }

  handlers:
    - name: Import Zabbix Database Dump
      become: true
      community.mysql.mysql_db:
        name: "{{ zabbix.server.database.name }}"
        state: import
        target: /usr/share/zabbix/sql-scripts/mysql/server.sql.gz
        login_user: "{{ zabbix.server.database.user }}"
        login_password: "{{ zabbix.server.database.password }}"
        login_host: "{{ zabbix.server.database.host }}"
        login_port: "{{ zabbix.server.database.port }}"

    - name: Restart Zabbix Server
      become: true
      ansible.builtin.service:
        name: zabbix-server
        state: restarted

    - name: Restart Apache2
      become: true
      ansible.builtin.service:
        name: apache2
        state: restarted
