---
- name: Running Zabbix Server Playbook
  hosts:
  vars_files:
    - variables/system/url.yml
    - variables/system/certificate.yml
    - variables/config/zabbix-server.yml
  tasks:
    - name: Install Zabbix repository
      become: true
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb

    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Zabbix server, FrontEnd, Agent2, PHP and Zabbix Agent2 plugins
      become: true
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-sql-scripts
          - zabbix-agent2
          - python3-pymysql
          - php
          # Install Zabbix Agent2 plugins
          - zabbix-agent2-plugin-mongodb
          - zabbix-agent2-plugin-mssql
          - zabbix-agent2-plugin-postgresql

    - name: Enable Apache2, Zabbix server and agent server
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent2

    - name: Create Zabbix database
      become: true
      community.mysql.mysql_db:
        name: "{{ database.name }}"
        state: present
        login_user: "{{ RemoteAdminDatabase.Username }}"
        login_password: "{{ RemoteAdminDatabase.Password}}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"
        encoding: utf8mb4
        collation: utf8mb4_bin
      notify: Import Zabbix Database Dump

    - name: Create MySQL users
      become: true
      community.mysql.mysql_user:
        login_user: "{{ RemoteAdminDatabase.Username }}"
        login_password: "{{ RemoteAdminDatabase.Password}}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"
        column_case_sensitive: true
        name: "{{ database.user }}"
        password: "{{ database.password }}"
        host: "%"
        priv:
          "{{ database.name }}.*:ALL"
        state: present

    - name: Select query to test_db with named_args
      community.mysql.mysql_query:
        login_user: "{{ RemoteAdminDatabase.Username }}"
        login_password: "{{ RemoteAdminDatabase.Password }}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"
        query: SET GLOBAL log_bin_trust_function_creators = 1;

    - name: Configuring locale
      become: true
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Running Apache2 role
      ansible.builtin.include_role:
        name: apache2
      vars:
        IsHttpsEnabled: true
        RedirectHttpsIsEnabled: true
        path: "/usr/share/zabbix/ui"
        AddinatalConfig: |
          AllowEncodedSlashes On
          php_value post_max_size 16M
          php_value max_execution_time 300
          php_value max_input_time 300

    - name: Configuring Zabbix Server
      become: true
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#?\\s*{{ item.option }}="
        line: "{{ item.option }}={{ item.value }}"
      notify: Restart Zabbix Server
      loop:
        - { option: DBHost, value: "{{ database.host }}" }
        - { option: DBPort, value: "{{ database.port }}" }
        - { option: DBName, value: "{{ database.name }}" }
        - { option: DBUser, value: "{{ database.user }}" }
        - { option: DBPassword, value: "{{ database.password }}" }

  handlers:
    - name: Import Zabbix Database Dump
      become: true
      community.mysql.mysql_db:
        name: "{{ database.name }}"
        state: import
        target: /usr/share/zabbix/sql-scripts/mysql/server.sql.gz
        login_user: "{{ database.user }}"
        login_password: "{{ database.password }}"
        login_host: "{{ database.host }}"
        login_port: "{{ database.port }}"

    - name: Restart Zabbix Server
      become: true
      ansible.builtin.service:
        name: zabbix-server
        state: restarted
