---
ip_address: "{{ ansible_default_ipv4.address }}"
domain_name:

app:
  env:
  debug:
  key:
  theme:
  timezone:
  url:
  locale:
  environment_only:

database:
  engine: mysql
  host:
  port:
  name:
  user:
  password:

redis:
  host:
  port:
  password:
