---
database:
  engine: "mysql"
  host:
  port:
  name:
  user:
  password:

multisiteIsEnabled: false

# https://api.wordpress.org/secret-key/1.1/salt/
auth_key:
secure_auth_key:
logged_in_key:
nonce_key:
auth_salt:
secure_auth_salt:
logged_in_salt:
nonce_salt:
