---
- name: Install needed dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-cryptography

- name: Generate Private Key
  become: true
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{ private_key }}"
    size: 4096
    type: RSA
    owner: root
    group: "ssl-cert"
    mode: "0640"

- name: Generate CSR
  become: true
  community.crypto.openssl_csr:
    path: "/etc/ssl/{{ csr }}"
    privatekey_path: "/etc/ssl/private/{{ private_key }}"
    country_name: "{{ subject.country }}"
    state_or_province_name: "{{ subject.state }}"
    locality_name: "{{ subject.city }}"
    organization_name: "{{ subject.organization }}"
    organizational_unit_name: "{{ subject.organizational_unit }}"
    common_name: "{{ subject.common_name }}"
    subject_alt_name:
      - "DNS:{{ domain_name }}"
      - "IP:{{ ip_address }}"

    owner: root
    group: root
    mode: "0644"

- name: Read CSR
  ansible.builtin.slurp:
    src: "/etc/ssl/{{ csr }}"
  register: csr_file

- name: Generate sighed public key
  become: true
  ansible.builtin.uri:
    remote_src: true
    url: "{{ post_sighed }}"
    method: POST
    body_format: form-multipart
    body:
      DomainName: "{{ domain_name }}"
      CertificateSigningRequest:
        filename: "{{ csr }}"
        content: "{{ csr_file.content | b64decode }}"
        mime_type: text/plain
    return_content: true
  register: response

- name: Write response to public key
  become: true
  ansible.builtin.copy:
    content: "{{ response.content }}"
    dest: "/etc/ssl/certs/{{ public_key }}"
    owner: root
    group: root
    mode: "0644"
