---
- name: Generate Private key
  become: true
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{ item.domain_name }}.key"
    size: 4096
    type: RSA
    owner: root
    group: ssl-cert
    mode: "0600"

- name: Generate CSR
  become: true
  community.crypto.openssl_csr:
    path: "/etc/ssl/{{ item.domain_name }}.csr"
    privatekey_path: "/etc/ssl/private/{{ item.domain_name }}.key"
    common_name: "{{ item.domain_name }}"
    subject_alt_name:
      - "DNS:{{ item.domain_name }}"
    owner: root
    group: root
    mode: "0644"

- name: Read CSR
  ansible.builtin.slurp:
    src: "/etc/ssl/{{ item.domain_name }}.csr"
  register: csr_data

- name: Getting certificates list from cloudflare
  ansible.builtin.uri:
    url: https://api.cloudflare.com/client/v4/certificates?zone_id={{ nginx.cloudflare.zones[item.domain_name.split('.')[-2:] | join('.')] }}
    method: GET
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ nginx.cloudflare.api_token }}
    return_content: true
  register: certificates_list

- name: Extract hostnames
  ansible.builtin.set_fact:
    cloudflare_hostname_list: "{{ certificates_list.json | default([]) | community.general.json_query('result[*].hostnames[0]') }}"

- name: Request new certificate
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/certificates?zone_id={{ nginx.cloudflare.zones[item.domain_name.split('.')[-2:] | join('.')] }}"
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ nginx.cloudflare.api_token }}"
    body_format: json
    body:
      csr: "{{ csr_data.content | b64decode }}"
      hostnames:
        - "{{ item.domain_name }}"
      request_type: origin-rsa
      requested_validity: 90
    return_content: true
  register: new_cert
  when: "item.domain_name not in cloudflare_hostname_list"

- name: Save new certificate
  become: true
  ansible.builtin.copy:
    content: "{{ new_cert.json.result.certificate }}"
    dest: "/etc/ssl/certs/{{ item.domain_name }}.crt"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx
  when: "item.domain_name not in cloudflare_hostname_list"

- name: Deploy nginx config
  become: true
  ansible.builtin.copy:
    content: |
      server {
        listen 80;
        server_name {{ item.domain_name }};
        return 301 https://$server_name$request_uri;
      }

      server {
        listen 443 ssl http2;
        server_name {{ item.domain_name }};

        ssl_certificate /etc/ssl/certs/{{ item.domain_name }}.crt;
        ssl_certificate_key /etc/ssl/private/{{ item.domain_name }}.key;

        location / {
            proxy_pass {{ item.proxy }};
            include proxy_params;
        }
      }
    dest: "/etc/nginx/sites-enabled/{{ item.domain_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx
