domain_name:
ip_address:

nextcloud_path: /var/www

database_connection:
  { 
    type: ,
    host: ,
    port: ,
    name: ,
    user: ,
    password: ,
  }

admin_credential:
  {
    user: ,
    password: ,
  }

trusted_domains: []