domain_name:
ip_address:

database_connection:
  { 
    type: ,
    host: ,
    port: ,
    name: ,
    user: ,
    pass: ,
  }

# https://api.wordpress.org/secret-key/1.1/salt/
AUTH_KEY:
SECURE_AUTH_KEY:
LOGGED_IN_KEY:
NONCE_KEY:
AUTH_SALT:
SECURE_AUTH_SALT:
LOGGED_IN_SALT:
NONCE_SALT: